### ISSUE TITLE
Can not use this plugin in a new react app

### ISSUE THREAD

**Issue by shkhalid** [jvas28/grapesjs-echarts#35]
I am getting the following error when use this plugin:

```
Uncaught TypeError: Cannot create property 'event' on string 'parallelAxisExpand'
    at Object.C [as registerAction] (echarts.js:2050:1)
    at Object.<anonymous> (parallelAxisAction.js:64:1)
    at e2 (bootstrap:19:1)
```

**Comment by jvas28** [comment]
Hi @shkhalid can I have some snippets on how you are using in on react, so I can help?

**Comment by shkhalid** [comment]
Hey @jvas28 thanks!

I just migrate my app from webpack to  vite.  The app starts working after commenting out this plugin.

**Comment by jvas28** [comment]
Fixed in 56ec8f3 / 76fb886 (pushed to `master`).

Root cause: this plugin used to bundle its own copy of `echarts` as a regular dependency. When your app also depends on `echarts` (which any React/Vite/webpack app using this plugin needs to), the bundler ends up with **two separate, disconnected copies of echarts** — one inside this plugin's bundle, one in your app. Errors like `Cannot create property 'event' on string 'parallelAxisExpand'` are a classic symptom of two echarts instances stepping on each other's internal registries.

The fix: `echarts` (and `grapesjs`) are now declared as **peer dependencies** instead of being bundled. Install `echarts` in your own app (`npm i echarts`) alongside this plugin, and there will only ever be one shared instance — this mirrors how `grapesjs` itself was already handled.

If you pull the latest `master` and still see this in your Vite/React setup, please reopen with a minimal repro and I'll take another look.
